### ISSUE TITLE
16299.15 search not working

### ISSUE THREAD

**Issue by weiyideai520** [da2x/EdgeDeflector#24]
click Cortana news it working，but search not working
 windows 10 1709（16299.15）

**Comment by da2x** [comment]
Please update to the [latest release](https://github.com/da2x/EdgeDeflector/releases/latest) (1.1.1.0) which should resolve this issue.

**Comment by weiyideai520** [comment]
but still not working 。。。
------------
i find，if i search key incloud chinese will not working
eq:
key: chinese can work
ket:中国 not work

**Comment by da2x** [comment]
I just tested and verified this. URL encoding of Chinese characters work just fine. Tested with Chrome, Brave, Vivaldi, Internet Explorer, and Firefox.

**Comment by weiyideai520** [comment]
![345](https://user-images.githubusercontent.com/2784569/31751265-0b55273c-b4b7-11e7-8d33-05e15a7b70f3.gif)
like this，flash past

**Comment by da2x** [comment]
For the issue with searches in Chinese not working, see issue #32.
